
param = {
    "user":{
        "create":{
            "url":"/api/v1/user/create",
            "method":"POST"
        },
        "upadte":{
            "url":"/api/v1/user/upadte",
            "method":"PUT"
        },
        "userlist":{
            "url":"/api/v1/user/users",
            "method":"GET"
        }
    },
    "hostgroup":{
        "create":{
            "url":"/api/v1/hostgroup",
            "method":"POST"
        },
        "get":{
            "url":"/api/v1/hostgroup",
            "method":"GET"
        },
        "patch":{
            "url":"/api/v1/hostgroup/",
            "method":"PATCH"
        }
    }
}